name: tflint-serverless

on:
  push:
    branches:
      # TODO: replace this if you are not using 'main' as your target
      # branch for pull requests.
      - main
permissions:
  pull-requests: write
  contents: write
  repository-projects: write    
jobs:
  tflint-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.29.0
      - name: Install Terraform plugins
        run: tflint --init
      - name: Lint Terraform files
        run: |
          tflint --deep --error-with-issues > tflint_report.json       
          cat tflint_report.json
